production:
  adapter: postgresql
  encoding: unicode
  database: lee_production
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: lee_development
  pool: 5
  # username: postgres
  # password: <%= ENV['POSTGRESPASSWORD'] %>
